version: '2'
services:
    reverseproxy:
        image: rrjamesjr/reverseproxy
        ports:
            - 8080:8080
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: dmuharemov1/nrs7_dz:1.0
        ports:
            - 8083:8080
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: dmuharemov1/bulletin:1.0
        ports:
            - 8085:8082
        restart: always